### ISSUE TITLE
Clothing Restricted by Branch

### ISSUE THREAD

**Issue by Xelakian** [cebutris/MithraBayport#62] opened 2018-12-16 18:51 UTC
#### Description of issue
Many clothing options are still restricted by branch/job/species, even when those restrictions shouldn't exist.

#### Difference between expected and actual behavior
Expected to be able to wear a jumpsuit as a Prospector, for instance. Was unable to.

#### Steps to reproduce 
Choose a job, choose loadout items, load into the game.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by cebutris** [comment] 2018-12-17 05:09
Duplicate of #51, which has already been fixed

**Closed as completed by cebutris** 2018-12-17 05:09 UTC
